kill_allowed: true
sessions:
  raspbee:
    user: pi
    host: 192.168.0.133 # raspbee
    key_file: raspbee/raspbee_key
    serial_devices:
      /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:
        baudrate: 115200
        mode: tcp
        port: 6667
        options:
          remote: raw,echo=0,nonblock
          # local: bind=172.17.0.1,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5,fork
          local: bind=127.0.0.1,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5,fork
      /dev/ttyAMA0:
        enable: false
        baudrate: 115200
        mode: pty
        path: /usr/share/hassio/addons/data/a0d7b954_zwavejs2mqtt/ttyAMA0
        options:
          remote: rawer,echo=0,nonblock
          local: rawer

